default:
    @just --list --list-submodules

#=======================================================================
# Local Checks
# Run directly on the host for speed as these recipes don't need
# infrastructure
# =======================================================================

test *ARGS:
    uv run pytest {{ ARGS }}

lint: setup
    uv run ruff check jamflow tests

formatcheck: setup
    uv run ruff format --check jamflow tests

typecheck: setup
    uv run ty check .

start: setup
    uv run fastapi dev jamflow/main.py

setup:
    uv sync --frozen --all-groups
