[project]
name = "JamFlow-backend"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  # Web
  "fastapi[standard]>=0.115.7",
  "uvicorn>=0.34.0",
  # Configuration
  "pydantic-settings>=2.7.1",
  # Database
  "asyncpg>=0.30.0",
  "sqlmodel>=0.0.22",
  "alembic>=1.14.1",
  # Logging
  "structlog>=25.1.0",
  # File storage
  "aiobotocore>=2.19.0",
  # Audio processing
  "filetype>=1.2.0",
  "mutagen>=1.47.0",
  "pydub>=0.25.1",
  "audioop-lts>=0.2.1",
]

[dependency-groups]
dev = [
  # Type checking
  "ty~=0.0.32",
  "types-aiobotocore[s3]>=2.19.0",
  # Code quality
  "pre-commit>=4.1.0",
  "ruff>=0.9.3",
  "rich>=13.9.4",
]
test = [
  # Testing
  "pytest>=9.0.3",
  "httpx>=0.28.1",
  "pytest-asyncio>=0.25.3",
  "pytest-mock>=3.14.0",
  "pytest-structlog>=1.1",
  "aiosqlite>=0.21.0",
  "polyfactory>=3.3.0",
]

[tool.ty.src]
exclude = ["./migrations"]

[tool.ruff]
exclude = [
  "migrations/versions/*", # don't lint generated migration code
]

[tool.ruff.lint]
# activate all rules and ignore what we don't care about
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
  "E501",   # line too long, handled by formatter
  "COM812", # trailing commas are formatter concern
  # TODO: reconsider this ignore
  "B008",  # do not perform function calls in argument defaults
  "UP035", # warn about deprecated imports, we still want to import type hints from typing
  # we don't lint for docstrings in for all that is public
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "TD003",  # we don't use issue numbers
  "TD002",  # it's ok not have authors in TODO
  "FIX",    # we are ok with TODO and FIXME comments
  "RET504", # unnecessary assigns can make debugging easier
  "PTH123", # it's fine to use `open`
  "EM",     # slight error message duplication in tracebacks are fine
  "TRY003", # we don't want to move all exception string construction into __init__
  "ANN204", # no need to provide return tupes for special methods
  # TODO: resolve below
  "DTZ",
  "PT011",
]

[tool.ruff.lint.per-file-ignores]
"migrations/env.py" = [
  "F403", # Ignore star import for migration generation
]
"jamflow/core/config.py" = [
  "N802", # config may have unconventional function names
]
"tests/**/*.py" = [
  "ANN",      # tests don't need to be strictly annotated
  "ASYNC230", # allow sync file operations in test
  "S101",     # allow asserts in tests
  "ARG002",   # fakes objects may have unused function parameters
  "PLR2004",  # test asserts can use magic values
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[tool.pytest.ini_options]
# https://pytest-asyncio.readthedocs.io/en/latest/reference/configuration.html
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
# https://docs.pytest.org/en/stable/how-to/capture-warnings.html#controlling-warnings
filterwarnings = ["ignore::DeprecationWarning:botocore.auth"]
