import uuid
from typing import BinaryIO, Protocol, Sequence

from jamflow.core.protocols import Repository
from jamflow.infra.audio import AudioMimeType
from jamflow.recordings.models import AudioFileFormat, Clip, Track


class TrackRepository(Repository[Track], Protocol): ...


class ClipRepository(Repository[Clip], Protocol):
    async def list_by_track_id(self, track_id: uuid.UUID) -> Sequence[Clip]: ...


class AudioProcessor(Protocol):
    def get_format(self, file: BinaryIO) -> AudioFileFormat: ...
    def get_duration(self, file: BinaryIO, file_format: AudioFileFormat) -> int: ...
    def get_size(self, file: BinaryIO) -> int: ...
    def get_mime_type(self, file_format: AudioFileFormat) -> AudioMimeType: ...
    def clip(
        self, file: BinaryIO, file_format: AudioFileFormat, *, start: int, end: int
    ) -> BinaryIO: ...
