name: Frontend Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install just
        uses: extractions/setup-just@v3

      - name: Build frontend
        run: just frontend build
