name: Frontend Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          package-json-file: frontend/package.json
          runtime: node@24
          install: false
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Run tests
        run: just frontend test
