name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: jamflowdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d jamflowdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t jamflow-backend ./backend
      - name: Run tests
        run: |
          docker run \
            --rm \
            --network host \
            -e DB_HOST=localhost \
            -e DB_PORT=5432 \
            -e DB_USER=postgres \
            -e DB_PASSWORD=password \
            -e DB_NAME=jamflowdb \
            -e DB_ROOT_NAME=postgres \
            -e DB_ROOT_NAME=postgres \
            -e STORAGE_URL=http://localhost:9000/ \
            -e STORAGE_ACCESS_KEY=replace-me \
            -e STORAGE_SECRET_KEY=with-a-real-key \
            jamflow-backend \
            pytest
